### ISSUE TITLE
Options `where_single_line` and `SameLineWhere` not working together

### ISSUE THREAD

**Issue by troplin** [rust-lang/rustfmt#2323]
With the following options:
```toml
brace_style = "SameLineWhere"
where_single_line = true
```
the opening brace is placed on the same line after the single-line `where` instead of on the next line.
