### ISSUE TITLE
Impossible single-line functions with AlwaysNextLine braces

### ISSUE THREAD

**Issue by Kibouo** [rust-lang/rustfmt#2835]
Using the options
``` toml
brace_style = "AlwaysNextLine"
fn_single_line = true
```
causes small functions to not become 1-liners, as such
``` Rust
fn lorem() -> usize
{
    42
}
```

I expected it to result in
``` Rust
fn lorem() -> usize { 42 }
```
as ``fn_single_line`` is the exception here. (Exceptions should overrule default settings.)

Version info:
``` bash
~ rustfmt -V 
rustfmt 0.8.2-nightly (5e59925 2018-07-02)
```

Is this intended behaviour?
