### ISSUE TITLE
Search for config file starts from current directory, not from location of formatted file

### ISSUE THREAD

**Issue by Vurich** [rust-lang/rustfmt#3196]
Currently, searching for `rustfmt.toml` will start from the current directory, meaning that running `rustfmt` on a file from outside the current project will use the wrong config. This was a problem for me because my editor's formatting command just runs `rustfmt path/to/current_file` with the current directory inherited from the editor process, and so the configuration used to format the file was incorrect until I ran `:cd path/to/current_project`

**Comment by scampi** [comment]
- tested with 7650f0bc8bbf8addf734dc3b0379c8bcb130089c
- nightly-x86_64-unknown-linux-gnu
- rustc 1.35.0-nightly (e3428db7c 2019-03-31)

I tried the following tree, where I formated `test1/src/main.rs` from `test2`. The config file `test1/rustfmt.toml` is correctly taken. @Vurich Please reopen if you encounter errors still.

# Test Tree

```
test1/
├── src/
│  └── main.rs
├── Cargo.toml
└── rustfmt.toml
test2/
├── src/
│  └── main.rs
├── Cargo.toml
└── rustfmt.toml
```

# Config files

- `test1/rustfmt.toml`:

    ```toml
    wrap_comments = true
    comment_width = 50
    ```

- `test2/rustfmt.toml`:

    ```toml
    wrap_comments = true
    comment_width = 100
    ```
