### ISSUE TITLE
rustfmt-nightly failing to format match statement

### ISSUE THREAD

**Issue by bcmyers** [rust-lang/rustfmt#3319]
I recently wrote some Rust code that took a "rust module" `String` produced by the [`quote`](https://docs.rs/quote/0.6.11/quote/macro.quote.html) macro and pumped it through rustfmt-nightly programmatically to output a formatted "rust module" `String`. This worked great, except for one match statement, which didn't format correctly. I don't think the issue has anything to do with me using rustfmt programmatically inside rust code, as when I save the output to a file and run `cargo fmt` from the command line, the bad formatting remains. In any case, I don't need the file I'm producing to be pretty, but I figured this might be a bug in rustfmt-nightly; so wanted to let you know.

- rustfmt version: rustfmt-nightly 1.0.1
- input: the `String` produced by [this function](https://github.com/bcmyers/num-format/blob/v0.1.2/num-format-dev/src/create_module.rs)
- how i ran rustfmt-nightly: [this function](https://github.com/bcmyers/num-format/blob/v0.1.2/num-format-dev/src/rustfmt.rs)
- (seemingly incorrect) output: [here](https://github.com/bcmyers/num-format/blob/v0.1.2/src/format/locale.rs#L2751)

**Comment by topecongiro** [comment]
This seems to be caused long string literals whose length is larger than the max width on match arms.

You could try `format_strings` configuration option:

```rust
    config.set().format_strings(true);
```

**Comment by bcmyers** [comment]
Thanks @topecongiro, but that didn't seem to work.

Here's the config I used (which I got from `config.all_options().to_toml().unwrap()`):

```toml
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
indent_style = "Block"
wrap_comments = false
format_doc_comments = false
comment_width = 80
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_strings = true
format_macro_matchers = false
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = false
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
force_multiline_blocks = false
fn_args_density = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2018"
version = "One"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.0.1"
unstable_features = false
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
ignore = []
emit_mode = "Stdout"
make_backup = false
```
