### ISSUE TITLE
[unstable option] color

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3385]
Tracking issue for color

**Comment by topecongiro** [comment]
Will be removed in 2.0.

**Comment by karyon** [comment]
This was removed in 2.x in https://github.com/rust-lang/rustfmt/pull/4006, but needs to be re-decided in 1.x.

**Comment by lnshi** [comment]
With github actions, even with `--color=always` still the diff view is **NOT** colourful:
```
runs-on: ubuntu-latest
steps:
  - uses: actions-rs/toolchain@v1
    with:
      toolchain: stable
      override: true

  - uses: actions/checkout@v2

  - name: Test run bare cargo fmt
    run: >
      cargo fmt --all --manifest-path=rsmain/Cargo.toml
      -- --check --color=always
```
