### ISSUE TITLE
structured configuration

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3487]
Prior to rustfmt 1.0 we trimmed most of the configuration options for maintainability. I am ok to add some of them back, as long as they are orthogonal to other part of code (like `imports_indent`). `where` is not one of them, so it is unlikely that we add it back. Sorry.

If we were to add more options, I prefer those to be more structured rather than having plain namespace. E.g., something like the following:

```toml
# You can explicitly add [default] or omit it.
indent = "Block"

[fn]
indent = "Visual"

[struct.pattern]
width = 100

[struct.expr]
width = 0
```

and you will get:

```rust
fn foo(xxxxxxxxxxxxxxxxxxxxxxxxxx: u32,
       yyyyyyyyyyyyyyyyyyyyyyy: u32,
       zzzzzzzzzzzzzzzzz: u32)
{
    let Graphviz { label, caption, scale, width, height } = self.graphviz;
    /// ...
    let result = Ok(GraphvizGen {
        file,
        path,
        graphviz,
    });
    // ...
}
```

_Originally posted by @topecongiro in https://github.com/rust-lang/rustfmt/issues/3316#issuecomment-477614459_

**Comment by scampi** [comment]
# Motivation

- we need to have finer-grained configuration options in order to let people format their code as they like
- the 1st attempt at this relied on namespacing the options, however this came to be non-maintainable
- with a structured definition of the configuration, a user can tweak the code's formatting in ways that may not have been thought of, and which would have required yet another namespaced option to cater for that new need

# Design

- each block corresponds to a specific part of rust code, e.g., `[fn]` or `[struct.pattern]`
    - @topecongiro we need to define a list of supported blocks ?
- some options can be used in different blocks, with each block interpreting it as it sees fit, e.g., options `comment_width` and `inline_attribute_width` could be set via the `width` option within the `[comment]` and `[attribute]` blocks, resp. This gives flexibility of new format tuning points without requiring a new option.
- options put outside of a block (or in a `[default]` block) sets default values that can be overwritten in specific blocks, e.g., `indent` in the example.
- an option value at a block level is also applied to all children:

    ```toml
    width = 42

    [fn]
    # here width is 42

    [struct]
    width = 100

    [struct.pattern]
    # here width is 100

    [struct.expr]
    # here width is 100
    ```

# Implementation

- like today's `Config` struct but with the notion of default/block overwritten options
- the current configuration format should be supported
    - @topecongiro should we version the config's definition ?

# Actions

- [ ] list issues asking for finer-grained option and check these can be fixed with the proposed structured configuration
