### ISSUE TITLE
rustfmt didn't format macro

### ISSUE THREAD

**Issue by LEXUGE** [rust-lang/rustfmt#3704]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7309a87bb5e3598b7ca9e80fcb115d60

The code snippet above haven't been formatted by rustfmt.

I have tried remove the `parse` and use the ordinary way of writing that. However, it didn't change anything.

**Comment by topecongiro** [comment]
We need to specify the following options to format `macro_rules!`:

```toml
format_macro_matchers = true
format_macro_bodies = true
```

And even then rustfmt may not be able to format certain `macro_rules!`, especially those with unusual syntax.
