### ISSUE TITLE
Documentation code is not formatted when `format_code_in_doc_comments` is enabled.

### ISSUE THREAD

**Issue by olson-sean-k** [rust-lang/rustfmt#3751]
I'm using nightly build `1.4.4-nightly (0462008 2019-08-06)` of `rustfmt` with the following `rustfmt.toml`:

```toml
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
```

When invoked with `cargo +nightly fmt` using this configuration, `rustfmt` does **not** format code in documentation comments. This doesn't seem to agree with [the documentation](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_code_in_doc_comments) for the `format_code_in_doc_comments` setting. Could this be a bug?
