### ISSUE TITLE
Rustfmt breaks chained method calls that are below max_width

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#3784]
I set max_width to 100 but it breaks this line:
```rust
	let port = env::var("PORT").ok().and_then(|s| s.parse().ok()).unwrap_or(8080);
```
into:
```rust
	let port = env::var("PORT")
		.ok()
		.and_then(|s| s.parse().ok())
		.unwrap_or(8080);
```

**How can I prevent it from breaking these kind of lines that are below the max_width?**

My settings:
```toml
edition = "2018"
version = "Two"
max_width = 100
hard_tabs = true
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
```

If there is an internal `max_chain` limit, it should exposed to be configurable (also allow unlimited = only use max_width for breaking lines).
