### ISSUE TITLE
rustfmt eats my blank lines way too often.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rustfmt#3928]
Often times rustfmt will eat the blank lines between code.

Example:

```rust
impl<'a> DisassemblyIterator<'a> {
  const ONE: core::num::Wrapping<u16> = core::num::Wrapping(1);

  fn new(system: &'a Terbium) -> Self {
    Self {
      system,
      pc: core::num::Wrapping(system.cpu.pc),
    }
  }
}
```

This will delete the line between the const and the new when I save the file and rustfmt runs. Except if there's _two_ blank lines it'll delete one and leave the other. I wish that rustfmt would never delete the _last_ blank line between things. If there's more than one that's fine to merge I guess, but I put the vertical space there for a reason so I want to keep at least 1 last blank line there.

* **Version:** rustfmt 1.4.9-nightly (33e36670 2019-10-07)

rustfmt.toml
```toml
error_on_line_overflow = false
merge_imports = true
reorder_imports = true
use_try_shorthand = true
tab_spaces = 2
max_width = 100
color = "Never"
```
