### ISSUE TITLE
Incorrect indentation when using `return` in a macro

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rustfmt#3936]
This macros is formatted using rustfmt:
```rust
macro_rules! m {
	($a:expr) => {
		if $a {
			return;
			}
	};
}
```
That closing curly bracket under the return clearly has to be one indented one level less.

Config used:
```toml
hard_tabs = true
use_small_heuristics = "Off"
```
