### ISSUE TITLE
comment-intentation regressions

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#4049]
After I updated to `rustfmt 1.4.11-nightly (18382352 2019-12-03)`, I noticed some comment-intentation regressions:

Before:
```rust
			if let Some(MpcEv::PlayDrum(pitch, vel)) =
				// self.mpc.handle_input(e, /*btn_ctrl_down,*/ tx_launch_to_daw, state_view)
				self.mpc.handle_input(e, &mut MyBorrowedState { tx_launch_to_daw, state_view })
			{
```
After:
```rust
			if let Some(MpcEv::PlayDrum(pitch, vel)) =
				// self.mpc.handle_input(e, /*btn_ctrl_down,*/ tx_launch_to_daw, state_view)
			 self.mpc.handle_input(e, &mut MyBorrowedState { tx_launch_to_daw, state_view })
			{
```
And another one. 
Before:
```rust
				if let Some(e) =
					// self.note_input.handle_input(e, /*btn_ctrl_down,*/ tx_launch_to_daw, state_view)
					self.note_input.handle_input(e, &mut MyBorrowedState { tx_launch_to_daw, state_view })
				{
```
After:
```rust
				if let Some(e) =
					// self.note_input.handle_input(e, /*btn_ctrl_down,*/ tx_launch_to_daw, state_view)
				 self.note_input.handle_input(e, &mut MyBorrowedState { tx_launch_to_daw, state_view })
				{
```

Notice: It inserts a single space after tab-indentation. 

These are my settings:
```toml
edition = "2018"
version = "Two"
max_width = 110
newline_style = "Unix"
use_small_heuristics = "Max"
hard_tabs = true
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
spaces_around_ranges = true
overflow_delimited_expr = true
```
