### ISSUE TITLE
Last parameter in function signature misaligned

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4352]
When using `Visual` indent style, a multi-lined function signature with the first line exceeding `max_width`, the last parameter will be formatted with incorrect indentation

**Input**

rustfmt.toml
```toml
indent_style = "Visual"
# This can be anything, just using a shorter value than the default for an easier example
max_width = 30
```

```rust
fn exceeds_max_width_1<T: Foo>(
    a: T,
    b: u32,
    c: u32){
   
}
```

**Output**

```rust
fn exceeds_max_width_1<T: Foo>(
    a: T,
    b: u32,
c: u32){
    // ...
}
```

**Expected output**
Believe it should be something like the below, but either way the indentation of the `c` parameter is definitely off currently
```rust
fn exceeds_max_width_1<
    T: Foo,
>(
    a: T,
    b: u32,
    c: u32,
){
    // ...
}
```

**Meta**

- rustfmt version:  Can reproduce this with 1.4.19 and latest 2.0 version on master
- From where did you install rustfmt?:  Tested building from source as well as via rustup on nightly
