### ISSUE TITLE
rustfmt_lib = { git = "https://github.com/rust-lang/rustfmt" }

### ISSUE THREAD

**Issue by ctaggart** [rust-lang/rustfmt#4388]
In `Cargo.toml`, I have
```
[dependencies]
rustfmt_lib = "2.0.0-rc.2"
```

But that version does not compile and I'd like to update to the latest `2.0.0` code, but this does not work:
``` toml
[dependencies]
rustfmt_lib = { git = "https://github.com/rust-lang/rustfmt" }
```

```
Camerons-MacBook-Pro:openapi_to_rust cameron$ cargo update
    Updating crates.io index
    Updating git repository `https://github.com/ctaggart/openapi`
    Updating git repository `https://github.com/rust-lang/rustfmt`
error: no matching package named `rustfmt_lib` found
location searched: https://github.com/rust-lang/rustfmt
required by package `openapi_to_rust v0.1.0 (/Users/cameron/rs/openapi_to_rust)`
```
