### ISSUE TITLE
Line comments turned into block comments despite `normalize_comments`

### ISSUE THREAD

**Issue by micouy** [rust-lang/rustfmt#4430]
**Input & expected output**

```rust
fn main() {
    match a {
        b => c,
        // b => c,
        // b => c,
    }
}
```

**Output**

```rust
fn main() {
    match a {
        b => c,
        /* b => c,
         * b => c, */
    }
}
```

**Config**
```toml
imports_layout = "HorizontalVertical"
max_width = 80
normalize_comments = true
match_arm_blocks = false
wrap_comments = true
blank_lines_upper_bound = 2
merge_imports = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
reorder_impl_items = true
```

Unfortunately I can't reproduce it in the playground.

EDIT: changed the example code

- rustfmt version: `rustfmt 1.4.21-nightly (01f2eadc 2020-09-04)`
- From where did you install rustfmt?: **rustup**
