### ISSUE TITLE
Formatting lots of derives doesn't respect max_width

### ISSUE THREAD

**Issue by CobaltCause** [rust-lang/rustfmt#4540]
**Input**
All of these reformat to the output shown below, even when adding `#![rustfmt::skip::attributes(derive)]` to the file

```rust
#[derive(Clone, PartialEq, Eq, Debug)]
#[derive(Serialize, Deserialize, IntoStaticStr, EnumKind)]
```

```rust
#[derive(
    Clone, PartialEq, Eq, Debug, Serialize, Deserialize, IntoStaticStr,
    EnumKind,
)]
```

**Output**
Note that the second line is over 80 characters long
```rust
#[derive(
    Clone, PartialEq, Eq, Debug, Serialize, Deserialize, IntoStaticStr, EnumKind,
)]
```

**Expected output**
By default I'd expect output that just makes a new line inside the derive, like this:
```rust
#[derive(
    Clone, PartialEq, Eq, Debug, Serialize, Deserialize, IntoStaticStr,
    EnumKind,
)]
```
I'd also expect `#![rustfmt::skip::attributes(derive)]` to leave the formatting alone in either of the above cases, but it appears to not do so.

**Meta**

- rustfmt version: `rustfmt 1.4.24-stable (eb894d5 2020-11-05)`
- From where did you install rustfmt?: `rustup`
- Configuration:

```toml
edition = "2018"
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
```
