### ISSUE TITLE
Imports get messed up: Closing brace is not inserted when grouping imports.

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rustfmt#4565]
**Describe the bug**

Imports get messed up: Closing brace is not inserted when grouping imports.

**To Reproduce**

Write this in a .rs file:
```rust
use crate::utils::audiodevices::*;
use crate::utils::configuration::Configuration;
use crate::utils::escape::FwSlashPipeEscape;
use crate::utils::local_ip_address::get_local_addr;
```
run rustfmt. Afterwards it shows this:
```rust
use crate::utils::{
    audiodevices::*;
use crate::utils::configuration::Configuration;
use crate::utils::escape::FwSlashPipeEscape;
use crate::utils::local_ip_address::get_local_addr;
```

**Expected behavior**
Correct import grouping.

**Meta**

- rustfmt version: `rustfmt 1.4.27-nightly (580d826e 2020-11-16)`
- From where did you install rustfmt?: rustup
- How do you run rustfmt: https://packagecontrol.io/packages/RustFmt

**Comment by calebcartwright** [comment]
I can't reproduce this locally nor on the playground (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=19843aa7fad8b082dc78840ab54175fc). Do you have any non-default config options set?

**Comment by Boscop** [comment]
@calebcartwright This is my config:
```toml
edition = "2018"
version = "Two"
max_width = 110
newline_style = "Unix"
use_small_heuristics = "Max"
hard_tabs = true
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
spaces_around_ranges = true

# compress vertically
overflow_delimited_expr = true
# fn_single_line = true
# fn_args_layout = "Compressed"

# force_multiline_blocks = true
# condense_wildcard_suffixes = true
# where_single_line = true
# comment_width = 0
# wrap_comments = true
```
