### ISSUE TITLE
format_code_in_doc_comments formats non-rust code

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rustfmt#4753]
**Config**

```toml
format_code_in_doc_comments = true
hard_tabs = true
```

**Input**

    /*!
    ```yaml
    foo:
      bar:
        rustfmt: "don't touch this"
    ```
    */

    fn main() {
    	println!("Hello, world!");
    }

**Output**

`cargo +nightly fmt` changes the indentation in front of the `rustfmt: "don't touch this"` line from 4 spaces to one tab. However, that code block specifies `yaml` as the language and should therefore not be touched by rustfmt.

**Meta**

- rustfmt version: `rustfmt 1.4.36-nightly (7de6968 2021-02-07)`
- From where did you install rustfmt?: rustup
