### ISSUE TITLE
Empty lines wrongly removed

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rustfmt#4930]
The empty line after the initial comment within the struct definition is there deliberately to separate it from the comments associated with the first attribute. rustfmt should not remove it, just as it preserves the choice i made to have empty lines between attributes for this struct.

```diff
 #[repr(C)]
 #[derive(Debug, Copy, Clone, PartialEq, Eq)]
 pub struct TimingInfo {
     /* NOTE: This struct must be directly usable by the C API, thus same attributes/layout/etc */
-
     /// The system clock time when this timing info structure was current.
     pub timestamp: Timeval,
 
     /// Non-zero if the local and the remote machine have synchronized clocks. If synchronized
     /// clocks are detected `transport_usec` becomes much more reliable. However, the code that
     /// detects synchronized clocks is very limited and unreliable itself.
     pub synchronized_clocks: i32,
 
     /// Time in usecs a sample takes to be played on the sink. For playback streams and record
     /// streams connected to a monitor source.
     pub sink_usec: MicroSeconds,
```

config:
```toml
brace_style = "SameLineWhere"
comment_width = 100
control_brace_style = "ClosingNextLine"
edition = "2018"
fn_args_layout = "Compressed"
hard_tabs = false
match_block_trailing_comma = true
max_width = 100
merge_derives = false
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_imports = false
group_imports = "StdExternalCrate"
reorder_modules = true
#struct_field_align_threshold = 20
tab_spaces = 4
trailing_comma = "Never"
use_small_heuristics = "Max"
use_try_shorthand = true
#where_single_line = true
wrap_comments = true
```
