### ISSUE TITLE
`merge_derives=false` ignored

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rustfmt#4934]
With the following config, reviewing the changes rustfmt made, I found an instance where `merge_derives = false` was ignored.

```toml
brace_style = "SameLineWhere"
comment_width = 100
control_brace_style = "ClosingNextLine"
edition = "2018"
fn_args_layout = "Compressed"
hard_tabs = false
match_block_trailing_comma = true
max_width = 100
merge_derives = false
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_imports = false
group_imports = "StdExternalCrate"
reorder_modules = true
#struct_field_align_threshold = 20
tab_spaces = 4
trailing_comma = "Never"
use_small_heuristics = "Max"
use_try_shorthand = true
#where_single_line = true
wrap_comments = true
```

```diff
 /// The state of a connection context.
 #[repr(C)]
-#[derive(Debug, Copy, Clone, PartialEq, Eq)]
-#[derive(FromPrimitive, ToPrimitive)]
+#[derive(Debug, Copy, Clone, PartialEq, Eq, FromPrimitive, ToPrimitive)]
 pub enum State {
     /* NOTE: This enum’s variants and variant values **must** remain identical to the `sys` crate
-       (C API) equivalent */
+    (C API) equivalent */
     /// The context hasn’t been connected yet.
     Unconnected,
     /// A connection is being established.
     Connecting,
     /// The client is authorizing itself to the daemon.
     Authorizing,
     /// The client is passing its application name to the daemon.
     SettingName,
     /// The connection is established, the context is ready to execute operations.
     Ready,
     /// The connection failed or was disconnected.
     Failed,
     /// The connection was terminated cleanly.
     Terminated,
 }
```

Version string: **unknown** (it was the nightly from the day I posted this)
Project: https://github.com/jnqnfe/pulse-binding-rust
Specific file: https://github.com/jnqnfe/pulse-binding-rust/blob/master/pulse-sys/src/context/mod.rs
Ran against the master branch after adding the quoted config.
