### ISSUE TITLE
Duplicate comma with `trailing_comma = "Always"` in struct pattern

### ISSUE THREAD

**Issue by dnbln** [rust-lang/rustfmt#5066]
```rust
// src/main.rs
fn main() {
    let Foo { a, .. } = b;
}
```
```toml
# rustfmt.toml
edition = "2021"

unstable_features = true
trailing_comma = "Always"
```

Reformat with `rustfmt --config-path rustfmt.toml src/main.rs`

```rs
// src/main.rs
fn main() {
    let Foo { a,, .. } = b;
}
```

`rustfmt --version`: `rustfmt 1.4.38-nightly (4961b10 2021-11-04)`
