### ISSUE TITLE
`imports_granularity = "Module"` breaks code which imports the same identifier twice with two different names

### ISSUE THREAD

**Issue by glittershark** [rust-lang/rustfmt#5224]
`rustfmt.toml`:
```toml
edition = "2018" # not sure if this is necessary for repro
imports_granularity = "Module"
```
`main.rs` (pre formatting):
```rust
use std::collections::HashMap;
use std::collections::HashMap as HM;

fn f(_: &HM<i32, i32>) {}
fn main() {
  let x = HashMap::new();
  f(&x);
}
```

`main.rs` (post formatting):
```rust
use std::collections::HashMap;

fn f(_: &HM<i32, i32>) {}
fn main() {
    let x = HashMap::new();
    f(&x);
}
```

removing the `HashMap as HM` alias causes the code to no longer compile.
