### ISSUE TITLE
`wrap_comments` wraps (long) headers

### ISSUE THREAD

**Issue by virtualritz** [rust-lang/rustfmt#5238]
Input (from the `miette` crate's docs):
```rust
/// # Wrapping Types That Do Not Implement `Error` (e.g. `&str` and `Box<dyn Error>`)
```

After `cargo fmt` with `rustfmt.toml`:
```toml
edition = "2021"
wrap_comments = true
format_code_in_doc_comments = true
```

Output:
```rust
/// # Wrapping Types That Do Not Implement `Error` (e.g. `&str` and `Box<dyn
/// Error>`)
```

Which renders as:
<img width="780" alt="Screen Shot 2022-02-25 at 15 57 09" src="https://user-images.githubusercontent.com/387036/155737116-c451468e-bdde-4618-a518-1f03542216a2.png">

# Fix

Do not ever break comment lines starting with `#` even when `wrap_comments` is set.
