### ISSUE TITLE
rustfmt doesn't work when using unstable feature bindeps

### ISSUE THREAD

**Issue by aviramha** [rust-lang/rustfmt#5332]
I started using the new feature [bindeps](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies) but can't get `cargo fmt` to run afterwards, complaining that cargo metadata failed. I tried running `cargo fmt -Z bindeps` but that doesn't seem to work. 

rust fmt version:
`rustfmt 1.4.38-nightly (69a5d248 2022-04-27)`

error:
```
`cargo metadata` exited with an error: error: failed to parse manifest at `/Users/aviramhassan/Code/mirrord/mirrord-cli/Cargo.toml`

Caused by:
  `artifact = …` requires `-Z bindeps` (mirrord-layer)
cargo-fmt 1.4.38
```

Reproducing:
Add to any cargo.toml the use of artifact:
```
mirrord-layer = { artifact = "cdylib", version = "0.1", path="../mirrord-layer" }
```

**Comment by calebcartwright** [comment]
I appreciate you reaching out, but short abstract descriptions like in your original post aren't exactly actionable.

At a minimum, please provide a minimal reproducible example, include any errors/failures you are seeing, share what version of rustfmt you are using (`rustfmt --version` or `cargo fmt --version`), etc.

**Comment by aviramha** [comment]
@calebcartwright Sorry! Thanks for being so polite, absolutely my bad. Updated the issue!

**Comment by calebcartwright** [comment]
No worries, and thanks for the additional detail. Have a theory but would you mind doing me a favor and updating your toolchain to the latest nightly and then running the following:

```
cargo metadata --manifest-path /Users/aviramhassan/Code/mirrord/mirrord-cli/Cargo.toml --format-version 1
```

**Comment by aviramha** [comment]
Updated to nightly (cargo 1.62.0-nightly (a44758ac8 2022-05-04))

```
cargo metadata
error: failed to parse manifest at `/Users/aviramhassan/Code/mirrord/mirrord-cli/Cargo.toml`

Caused by:
  `artifact = …` requires `-Z bindeps` (mirrord-layer)
```

**Comment by calebcartwright** [comment]
Thanks, one last request, can you run the same command but add the `--all-features` opt, and then share the contents of the Cargo.toml file?

**Comment by aviramha** [comment]
Same output..
```toml
[package]
name = "mirrord-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
mirrord-layer = { artifact = "cdylib", version = "0.1", path="../mirrord-layer" }
exec = "0.3"

```

**Comment by calebcartwright** [comment]
I expected as much but thanks for confirming! I need to check with the cargo team to figure out the best foot forward.

For a little more background, we own/maintain the `cargo fmt` subcommand, but it's essentially just a simple `rustfmt ...` command builder to make it easier for users to format their entire workspace/crate/package/etc. (analogous to `cargo build` being much more user-friendly than manual `rustc ...` invocations). In order to build out those `rustfmt` commands, `cargo fmt` internally runs a `cargo metadata ...` command, which is where the issue is surfacing

**Comment by calebcartwright** [comment]
Pretty solid suggestion from them is to utilize the cargo config file to set this so that all commands, including the one we issue, will pick it up automatically:

```toml
# .cargo/config.toml

[unstable]
bindeps = true
```

There's a couple of options we could take on our end to avoid needing that, but would rather not have to go down those routes without good reason. Give the above a try whenever you get a chance and let us know if it works for you
