### ISSUE TITLE
Formatting instability with --file-lines

### ISSUE THREAD

**Issue by gigaroby** [rust-lang/rustfmt#5340]
At work we've been using --file-lines and we just ran into what we think is a bug. Take for example a snippet like (simplified and does not compile):

```rust
fn GenerateBindingsImpl() {
    catch_unwind(|| {
        // It is ok to abort here.
        let Bindings { rs_api, rs_api_impl } = generate_bindings(json, **foobar_support_path**, &rustfmt_config_path).unwrap();
        FfiBindings {
            rs_api: FfiU8SliceBox::from_boxed_slice(rs_api.into_bytes().into_boxed_slice()),
            rs_api_impl: FfiU8SliceBox::from_boxed_slice(
                rs_api_impl.into_bytes().into_boxed_slice(),
            ),
        }
    })
}
```

The only change we make to this snippet is to add the foobar_support_path argument and so the version control system generates a --file-lines covering that line only: `rustfmt --config-path /tmp/rustfmt.toml --unstable-features --file-lines '[{"file": "stdin", "range": [4,4]}]'`

This does nothing to the snippet but by playing around with the range we can find out that changing the end line has no effect (easy to try by setting it to 100) but altering the start line to 2 or less will cause it to break the line as follows: 

`rustfmt --config-path /tmp/rustfmt.toml --unstable-features --file-lines '[{"file": "stdin", "range": [2,4]}]'`

```rust
fn GenerateBindingsImpl() {
    catch_unwind(|| {
        // It is ok to abort here.
        let Bindings { rs_api, rs_api_impl } =
            generate_bindings(json, foobar_support_path, &rustfmt_config_path).unwrap();
        FfiBindings {
            rs_api: FfiU8SliceBox::from_boxed_slice(rs_api.into_bytes().into_boxed_slice()),
            rs_api_impl: FfiU8SliceBox::from_boxed_slice(
                rs_api_impl.into_bytes().into_boxed_slice(),
            ),
        }
    })
}
```

The main problem with this is that editing the surrounding lines later will randomly cause these changes to appear, causing spurious diffs. This is the specific commit where we just re-formatted the entire file: https://github.com/google/crubit/commit/362348939b768235f08454cd9064ce5893067965

The `rustfmt.toml` config we use is as follows:
```toml
edition = "2021"
version = "Two"
# The "Default" setting has a heuristic which splits lines too aggresively.
# We are willing to revisit this setting in future versions of rustfmt.
# Bugs:
#   * https://github.com/rust-lang/rustfmt/issues/3119
#   * https://github.com/rust-lang/rustfmt/issues/3120
use_small_heuristics = "Max"

newline_style = "Unix"

wrap_comments = true
```
