### ISSUE TITLE
function cascade formatting

### ISSUE THREAD

**Issue by ignamartinoli** [rust-lang/rustfmt#5474]
Hi, I was trying to get my code formatted like this

```rust
fn main() {
	let numbers: Vec<i32> = ["one", "2", "3", "NaN"]
		.iter()
		.filter_map(|x| x.parse().ok())
		.collect();
}
```

but after running `rustfmt` I get

```rust
fn main() {
	let numbers: Vec<i32> =
		["one", "2", "3", "NaN"].iter().filter_map(|x| x.parse().ok()).collect();
}
```

This is my `rustfmt.toml` file

```toml
brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
trailing_comma = "Never"
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
```

I went through https://rust-lang.github.io/rustfmt but couldn't find anything to fix this. Is this feature lacking or I'm misconfiguring?
