### ISSUE TITLE
format_code_in_doc_comments ignores doc comments with /** */ syntax

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rustfmt#5530]
I used to prefer `/** */` syntax over `///` when I was using atom because it didn't have good support for the later. `rustdoc` happily accepts both doc comment styles. However, rustfmt does not seem to remove the space before a colon in function arguments in `/** */` doc comments. When using `///` instead, it works.

**src/lib.rs**

    /**
    ```rust
    fn read(id : i64) {}
    ```
    */
    pub struct Foo;

**rustfmt.toml**

```toml
version = "Two"
edition = "2021"
newline_style = "Unix"
unstable_features = true
format_code_in_doc_comments = true
```
