### ISSUE TITLE
Rustfmt "fixes" my code then tells me an error about the code it broke itself

### ISSUE THREAD

**Issue by laralove143** [rust-lang/rustfmt#5531]
My config:
```toml
unstable_features = true
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
use_field_init_shorthand = true
wrap_comments = true
```
Version: `rustfmt 1.5.1-nightly (84f0c3f7 2022-09-03)`

Hard to explain with text so here's a recording:
https://user-images.githubusercontent.com/82576556/188334072-8fb46dd0-e76c-46ce-8f03-8db6a08eb096.mov
