### ISSUE TITLE
repetition macro break whole macro format

### ISSUE THREAD

**Issue by tkkcc** [rust-lang/rustfmt#5534]
rustfmt 1.5.1-nightly (9243168 2022-08-31)

rustfmt.toml:
```toml
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
```

code won't format
```rust
macro_rules! test {
    ($( $v:expr ),*) => {
        $(      $v),*
    };
}
```
