### ISSUE TITLE
rustfmt does not respect brace_style when formatting imports

### ISSUE THREAD

**Issue by BenjaminBrienen** [rust-lang/rustfmt#5545]
With:
```toml
hard_tabs = true
braces_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
group_imports = "StdExternalCrate"
imports_granularity = "One"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
newline_style = "Unix"
trailing_comma = "Vertical"
```
Current output:
```rust
use {
	colored::{
		ColoredString,
		Colorize,
	},
	std::{
		cmp::Ordering,
		fmt::{
			Display,
			Formatter,
		},
		io::{
			Read,
			Write,
		},
		ops::{
			ControlFlow,
			RangeInclusive,
		},
		result::Result,
	},
};
```
Expected output:
```rust
use
{
	colored::
	{
		ColoredString,
		Colorize,
	},
	std::
	{
		cmp::Ordering,
		fmt::
		{
			Display,
			Formatter,
		},
		io::
		{
			Read,
			Write,
		},
		ops::
		{
			ControlFlow,
			RangeInclusive,
		},
		result::Result,
	},
};
```
