### ISSUE TITLE
rustfmt.toml config file issues

### ISSUE THREAD

**Issue by jvcmarcenes** [rust-lang/rustfmt#5589]
I've made some changes to rustfmt default configuration, and tried placing it under every place that the [Configuring Rust](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=) webpage points to, but the only location where the configuration file took effect was in the project workspace root (next to Cargo.toml).
while I wanted to modify configurations on every project globally.

Also, rustfmt won't respect the `tab_spaces` configuration, I have set it to 2, but it still insert 4 space tabs.

**Comment by ytmimi** [comment]
@jvcmarcenes sorry to hear that you're having issues. What version of rustfmt are you using and what platform are you developing on?

rustfmt will first start by checking the local directory for a configuration file, and if it doesn't find one it'll work its way up the file system looking for configuration files. If it finds one along the way it'll use that configuration, otherwise it'll do a final check in some platform specific configuration directories.

I don't know how your file system is laid out, but there's a chance that you may have a rustfmt.toml located somewhere in a parent directory that's preventing the configuration options from taking affect.

**Comment by ytmimi** [comment]
a similar issue was reported in #5471

**Comment by jvcmarcenes** [comment]
> @jvcmarcenes sorry to hear that you're having issues. What version of rustfmt are you using and what platform are you developing on?

Sorry, Forgot to specify.
I'm on Windows 11 22H2 (22621.755), using rustfmt 1.5.1-stable and cargo 1.65.0.

**Comment by jvcmarcenes** [comment]
Moving the .rustfmt.toml to Users/$USERNAME/.rustfmt.toml seems to have worked, but the tab_spaces configuration is not respected, it still applies 4 space tabing even with the key set to 2.
for reference, this is my .rustfmt.toml:
```toml
fn_single_line = true
format_macro_matchers = true
hard_tabs = true
inline_attribute_width = 80
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_width = 30
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Off"
```
