### ISSUE TITLE
rustfmt adds trailing whitespace on empty doc comment

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rustfmt#5614]
This happened today in a project of mine: https://github.com/msrd0/cargo-doc2readme/pull/194/commits/7bb7690f6e5cdfa0e2f5be9d5e9ab083fb759bd1#diff-b3a721d27023ff07c5331d85424a395ed8907cc619825e7698ef8e3b5bf2a363

**lib.rs**

```rust
//! blah blah
//!
//! ```toml
#![doc = r#"blahblah = "0.1.0""#]
//! ```
//!
//! | Header1  | Header2 |
//! |----------|---------|
//! | A        | B       |
#![doc = "| C | D |"]
//! | E        | F       |
//!
//! blah blah
```

**rustfmt.toml**

```toml
edition = "2021"
max_width = 90
newline_style = "Unix"
unstable_features = true
hard_tabs = true
tab_spaces = 4
match_block_trailing_comma = true
trailing_comma = "Never"
imports_granularity = "Crate"
format_code_in_doc_comments = true
format_macro_matchers = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
overflow_delimited_expr = true

# https://github.com/rust-lang/rustfmt/issues/3367
spaces_around_ranges = true
```

The problem cannot be reproduced with the default rustfmt configuration.

```
$ cargo +nightly fmt -- -V
rustfmt 1.5.1-nightly (b3bc6bf 2022-11-24)
```
