### ISSUE TITLE
RustFmt takes entire ram when formatting simple(broken) file

### ISSUE THREAD

**Issue by qarmin** [rust-lang/rustfmt#5752]
```
rustfmt 1.5.2-nightly (a41fc00 2023-04-13)
```
File
```
cfg_if::cfg_if! {
    if #[cfg(any(
        all(target_arch = "wasm32", not(target_os = "wasi")),
        target_arch = "asmjs"
    ))] {
        #[cfg(all(feature = "stdweb", not(feature = "wasm-bindgen")))]
        extern crate stdweb;

        mod wasm;
        pub use wasm::Instant;
        pub use crate::wasm::now;
        pub use wasm::SystemTime;
    } else {
        mod native;
        pub use native::Instant;
    %=    pub use native::now;
    }
}
```
will take 20GB ram and upset my oom killer which will kill process

**Comment by calebcartwright** [comment]
Could you tell us a little more about the context in which you're seeing this? I'm unable to reproduce anything remotely resembling the behavior you're describing, so it would be helpful to know things like, how are you running rustfmt (e.g. via your editor or `rustfmt file.rs`), what platform/os are you on?, etc.

**Comment by qarmin** [comment]
Hmm...

For me simple `rustfmt Broken/RUST_FILE_14086_06261.rs` cause this problem without any special arguments

Zipped file -  [RUST_FILE_14086_06261.rs.zip](https://github.com/rust-lang/rustfmt/files/11240583/RUST_FILE_14086_06261.rs.zip)

```
System:
  Host: rafal-H87M-D3H Kernel: 5.19.0-38-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 43.1 Distro: Ubuntu 22.10 (Kinetic Kudu)
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire driver: amdgpu v: kernel arch: GCN-4 bus-ID: 01:00.0
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland v: 22.1.3 driver:
    X: loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon RX 570 Series (polaris10 LLVM 15.0.7 DRM
    3.47 5.19.0-38-generic) v: 4.6 Mesa 22.3.5 (git-78ef633056)
    direct render: Yes
```
