### ISSUE TITLE
brace_style AlwaysNextLine fails on nightly

### ISSUE THREAD

**Issue by aspizu** [rust-lang/rustfmt#5912]
```toml
unstable_features = true
condense_wildcard_suffixes = true
edition = "2021"
max_width = 128
group_imports = "StdExternalCrate"
tab_spaces = 3
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
combine_control_expr = false
# condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity = "Crate"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
wrap_comments = true
use_small_heuristics = "Max"
trailing_comma = "Never"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
```
```
error[internal]: left behind trailing whitespace
   --> /home/aspizu/Projects/onyo/src/value.rs:207:207:1
    |
207 |
    | ^^^^^^^^^
    |

error[internal]: left behind trailing whitespace
   --> /home/aspizu/Projects/onyo/src/value.rs:472:472:1
    |
472 |
    | ^^^^^^^^^
    |

warning: rustfmt has failed to format. See previous 2 errors.
```

**Comment by calebcartwright** [comment]
Thanks for reaching out, but there's not enough here for us to be able to offer any insight. Please provide a complete and minimal reproducible example that includes the code snippet

**Comment by aspizu** [comment]
```rs
enum Amogus {
   A(usize),
   B(usize)
}

fn foo() {
   let bar = match Amogus::A(1) {
      Amogus::A(a) =>
         aaaaaaaaaaaaaaaaaaaaaaaA()
            + bbbbbbbbbbbbbbbbbbbbbbbbb()
            + bbbbbbbbbbbbbbbbbbbbbbbbb()
            + bbbbbbbbbbbbbbbbbbbbbbbbb()
            + bbbbbbbbbbbbbbbbbbbbbbbbb()
            + bbbbbbbbbbbbbbbbbbbbbbbbb()
            + bbbbbbbbbbbbbbbbbbbbbbbbb()
            + bbbbbbbbbbbbbbbbbbbbbbbbb(),
      Amogus::B(b) => 2
   };
}
```

```
error[internal]: left behind trailing whitespace
  --> /home/aspizu/Projects/onyo/foo.rs:12:12:1
   |
12 |       
   | ^^^^^^
   |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by GambitingMan** [comment]
It seems the error is caused by the following config settings
```toml
match_arm_blocks = false
control_brace_style = "AlwaysNextLine"
```
