### ISSUE TITLE
Fails in some deeply nested method chains sprinkled with indexing

### ISSUE THREAD

**Issue by berrymot** [rust-lang/rustfmt#6151]
Found in an attempt to format [this](https://github.com/berrymot/notoize/blob/e1d273c411af9b36a01acd9591b408b785320e77/src/lib.rs). Haven't found a minimal reproduction yet, sorry

![image](https://github.com/rust-lang/rustfmt/assets/50974538/df7d23ba-ebda-4a76-b1fb-3e34d434d9cd)

`rustfmt.toml`:

```toml
error_on_line_overflow = true
max_width = 100
imports_granularity = "Crate"
```

Version: `rustfmt 1.7.0-nightly (7f2fc33d 2024-04-22)`
