### ISSUE TITLE
Group imports together with imports_granularity results in non-idempotent formatting

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustfmt#6195]
When `group_imports = "StdExternalCrate"` is combined with `imports_granularity = "Module"`, `rustfmt` can format a file in a non-idempotent way, i.e. running `rustfmt` twice in a row results in a different formatting. 

Reduced from a case in the `stdlib` (https://github.com/rust-lang/rust/issues/126394).

Minimal repro:
```toml
# rustfmt.toml
version = "Two"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
```

```bash
$ rustfmt --version
rustfmt 1.7.0-nightly (72fdf91 2024-06-05)
```

```rust
# file.rs
use a::c;
// foo
use a::b;
use a::d;
```

First run (`rustfmt file.rs`):
```rust
// foo
use a::b;
use a::{c, d};
```

Second run (`rustfmt file.rs`):
```rust
// foo
use a::{b, c, d};
```

Removing the `group_imports` or `imports_granularity` options removes the issue. The problem seems to be caused by the comment, without it it works fine.
