### ISSUE TITLE
Feature Request: Visibility rewrites

### ISSUE THREAD

**Issue by andylovescode** [rust-lang/rustfmt#6222]
## Background
Frequently, when making a binary project, when I try to use something and forget to make it public, RustRover will give me a button to automatically make it public, but it makes it `pub(crate)`. For workspaces with only one crate, with that crate being a binary, it is functionally identical to `pub`, but more verbose.

## Request
Introduce a new option, `visibility_rewrites`, which is a table with optional keys `"public" | "crate" | "self" | "super" | "default"`, and the same as values (except the values are PascalCase because it's an enum).

This table acts as a replacement table for visibilities.

This does nothing to `pub ( in {} )` modifiers.

The default configuration for the property would just keep the existing visibility, like this:

```toml
[visibility_rewrites]
public = "Public"
crate = "Crate"
self = "Self"
super = "Super"
default = "Default"
```

### rustfmt.toml
```toml
[visbility_rewrites]
crate = "Public"
```

### main.rs
```rust
pub(crate) fn example() {
    todo!();
}
```

### output.rs
```rust
pub fn example() {
    todo!();
}
```

## Considerations
* This may be a bit too complicated, and we could just have a `rewrite_pub_crate` option.
    * This would also save people from accidentally rewriting public to default, which I doubt anyone would ever want.

Feedback is greatly appreciated!
