### ISSUE TITLE
Feature request: Add the option to configure rustfmt in the `Cargo.toml` metadata tables

### ISSUE THREAD

**Issue by J-Westin** [rust-lang/rustfmt#6296]
The `Cargo.toml` specification includes [`[project.metadata]` and `[workspace.metadata]` tables](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table), which allows external tools to store arbitrary data. These tables could be used to configure `rustfmt`, in addition to the existing `.rustfmt.toml` and `rustfmt.toml` files.

Configuration data for `rustfmt`, in the same format used in the existing `.toml` files, could be read from the `[package.metadata.rustfmt]` table. The following `rustfmt.toml` file:

```toml
max_width = 79
```

would be equivalent to the following `Cargo.toml`:

```toml
[package]
# ...

[dependencies]
# ...

[package.metadata.rustfmt]
max_width = 79
```
