### ISSUE TITLE
--print-config current with use_small_heuristics = "Off": Could not output config: out-of-range value for u64 type

### ISSUE THREAD

**Issue by antifuchs** [rust-lang/rustfmt#6364]
I'm attempting to detect whether a project has unstable rustfmt features configured, and was hoping to use rustfmt to detect that. However, with a config file like:

```toml
edition = "2021"

condense_wildcard_suffixes = true
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
max_width = 80
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
wrap_comments = true
```

running the following only prints an error:

```console
:;    rustfmt +nightly --print-config current main.rs
Could not output config: out-of-range value for u64 type
```

I would expect that config file to re-serialize correctly, as the formatter does do the work according to the config.
